/*global systemDictionary:true */
"use strict";

systemDictionary = {
    "pilight adapter settings": {
        en: "Adapter settings for pilight",
        de: "Adaptereinstellungen für pilight",
        ru: "Настройки адаптера для pilight",
        pt: "Configurações do adaptador para pilight",
        nl: "Adapterinstellingen voor pilight",
        fr: "Paramètres d'adaptateur pour pilight",
        it: "Impostazioni dell'adattatore per pilight",
        es: "Ajustes del adaptador para pilight",
        pl: "Ustawienia adaptera dla pilight",
        "zh-cn": "pilight的适配器设置",
    },
    "Server Username": {
        en: "Username HTTP access",
        de: "Benutzername HTTP Zugriff",
        ru: "?????? ? ????? ???????????? ?? ????????? HTTP",
        pt: "Acesso HTTP do nome de usu�rio",
        nl: "Gebruikersnaam HTTP-toegang",
        fr: "Nom d'utilisateur acc�s HTTP",
        it: "Nome utente accesso HTTP",
        es: "Nombre de usuario acceso HTTP",
        pl: "Nazwa uzytkownika Dostep HTTP",
        "zh-cn": "??? HTTP ??",
    },
    "Server Password": {
        en: "Password HTTP access",
        de: "Passwort HTTP Zugriff",
        ru: "?????? ??????? HTTP",
        pt: "Senha de acesso HTTP",
        nl: "Wachtwoord HTTP-toegang",
        fr: "Mot de passe acc�s HTTP",
        it: "Password di accesso HTTP",
        es: "Acceso HTTP con contrase�a",
        pl: "Haslo dostepu HTTP",
        "zh-cn": "?? HTTP ??",
    },
    "Server IP": {
        en: "IP from the Pilight server",
        de: "IP vom Pilight Server",
        ru: "IP ? ??????? Pilight",
        pt: "IP do servidor Pilight",
        nl: "IP van de Pilight-server",
        fr: "IP du serveur Pilight",
        it: "IP dal server Pilight",
        es: "IP del servidor Pilight",
        pl: "IP z serwera Pilight",
        "zh-cn": "?? Pilight ???? IP",
    },
    "Server HTTP PORT": {
        en: "HTTP port from Pilight server (default 5001)",
        de: "HTTP Port vom Pilight Server (Standard 5001)",
        ru: "HTTP-???? ? ??????? Pilight (???????? 5001)",
        pt: "Porta HTTP do servidor Pilight (padr�o 5001) ",
        nl: "HTTP-poort van Pilight-server (standaard 5001)",
        fr: "Port HTTP du serveur Pilight (standard 5001)",
        it: "Porta HTTP dal server Pilight (standard 5001)",
        es: "Puerto HTTP del servidor Pilight (est�ndar 5001)",
        pl: "Port HTTP z serwera Pilight (standard 5001)",
        "zh-cn": "?? Pilight ???? HTTP ??(?? 5001)",
    },
    "Server DAEMON PORT": {
        en: "Daemon port from the Pilight server ",
        de: "Daemon Port vom Pilight Server",
        ru: "???? ?????? ? ??????? Pilight",
        pt: "Porta daemon do servidor Pilight",
        nl: "Daemon-poort van de Pilight-server",
        fr: "Port du d�mon du serveur Pilight",
        it: "Porta del demone dal server Pilight",
        es: "Puerto de demonio del servidor Pilight",
        pl: "Port demona z serwera Pilight",
        "zh-cn": "?? Pilight ??????????",
    },
};
